### PR TITLE
Remove duplicate rows in annotate_sv output

### PR DESCRIPTION
**Pull request by vladimirsouza**
Changes that I made in this PR:

1. Some rows were duplicated because there were duplications in `sv_data` input argument (if using `GAMBLR.data::sample_data$grch37$bedpe`). I added a code to remove these duplicated rows at the beginning of `annotate_sv` code.
```
table( duplicated(GAMBLR.data::sample_data$grch37$bedpe) )
# FALSE  TRUE 
#  1031    14 
```

2. If both regions 1 and 2 are considered `gene` (oncogene) but they don't have a `partner`, we'll have duplicate rows (the most numerous case of duplication). I added code to remove those duplications. In the example, the first 4 rows are when `11:68878439-68878439` region is considered oncogene (gene `CCND1`), and the last 4 rows are when `11:68878445-68878445` is considered oncogene (also gene `CCND1`; they are a few bases away). PS: Rows 2 and 3 are duplicates for some other reason.
```
all.annotated
#    chrom1   start1     end1 chrom2   start2     end2 name score strand1 strand2 tumour_sample_id  gene partner   fusion
# 1:     11 68878439 68878439     11 68878445 68878445    .    55       +       -        08-15555T CCND1    <NA> NA-CCND1
# 2:     11 68878439 68878439     11 68878445 68878445    .    54       +       -        10-27119T CCND1    <NA> NA-CCND1
# 3:     11 68878439 68878439     11 68878445 68878445    .    54       +       -        10-27119T CCND1    <NA> NA-CCND1
# 4:     11 68878439 68878439     11 68878445 68878445    .    53       +       -        14-14094T CCND1    <NA> NA-CCND1
# 5:     11 68878439 68878439     11 68878445 68878445    .    55       +       -        08-15555T CCND1    <NA> NA-CCND1
# 6:     11 68878439 68878439     11 68878445 68878445    .    54       +       -        10-27119T CCND1    <NA> NA-CCND1
# 7:     11 68878439 68878439     11 68878445 68878445    .    54       +       -        10-27119T CCND1    <NA> NA-CCND1
# 8:     11 68878439 68878439     11 68878445 68878445    .    53       +       -        14-14094T CCND1    <NA> NA-CCND1

unique(all.annotated)   # only different `tumour_sample_id`
#    chrom1   start1     end1 chrom2   start2     end2 name score strand1 strand2 tumour_sample_id  gene partner   fusion
# 1:     11 68878439 68878439     11 68878445 68878445    .    55       +       -        08-15555T CCND1    <NA> NA-CCND1
# 2:     11 68878439 68878439     11 68878445 68878445    .    54       +       -        10-27119T CCND1    <NA> NA-CCND1
# 3:     11 68878439 68878439     11 68878445 68878445    .    53       +       -        14-14094T CCND1    <NA> NA-CCND1
```

3. Cases when a gene is considered oncogene and partner (CIITA in the example). But when oncogene, there is no partner. I removed the rows with NA for `partner`. Please, see whether this is the desirable change.
```
   chrom1   start1     end1 chrom2   start2     end2 name score strand1 strand2 tumour_sample_id    gene partner        fusion
1:     13 91975699 91975699     16 10980639 10980639    .    73       +       +         SP124973 MIR17HG   CIITA CIITA-MIR17HG
2:     13 91975699 91975699     16 10980639 10980639    .    73       +       +         SP124973   CIITA    <NA>      NA-CIITA
```

4. When gene `A` is classified as oncogene and gene `B` as `A`'s partner, and also vice-versa, e.g.
```
    chrom1    start1      end1 chrom2   start2     end2 name score strand1 strand2 tumour_sample_id  gene partner     fusion
 1:      3 187466157 187466157     16 10969379 10969379    .   204       +       +        14-41461T  BCL6   CIITA CIITA-BCL6
 2:      3 187466157 187466157     16 10969379 10969379    .   204       +       +        14-41461T CIITA    BCL6 BCL6-CIITA
```
I keep the row that, in the `gene` column, contains the gene (`A` or `B`) with the highest priority to be classified as an oncogene. This priority is defined in the internal vector `priority_to_be_oncogene <- c("MYC", "BCL6")`, where genes to the left have higher priority and non-listed genes have the same lowest priority (maybe this object could be an argument if we want to give the user freedom to change it).

### CODE REVIEW

**Comment by vladimirsouza** [comment]
Now I understand that the third change described in my first comment in this PR (_"Cases when a gene is considered oncogene and partner ... But when oncogene, there is no partner"_) should be discarded. Is this right?

**Comment by vladimirsouza** [comment]
* When case 3 (_... a gene is considered oncogene and partner (CIITA in the example). But when oncogene, there is no partner ..._), described in my first post in this PR, I changed `annotate_sv` to not filter out any row. 

* If there are two rows with the same values, but inverted ones for the `gene` and `partner` columns (i.e. both genes are partners of each other), and neither of them is MYC or BLC6 (genes listed in the `priority_to_be_oncogene` object), keep both rows. To recap: If in a similar case, but one of the genes is MYC or BLC6, keep the row where MYC is oncogene &mdash; first priority &mdash; or BCL6 is oncogene &mdash; second priority. 

* changed `for` loops to `lapply`-like loops

* better error track

**Comment by Kdreval** [comment]
Thank you @vladimirsouza ! Can you please post an example of how the case 4 from your original post in this PR is handled now? I am thinking of these rows:
```
    chrom1    start1      end1 chrom2   start2     end2 name score strand1 strand2 tumour_sample_id  gene partner     fusion
 1:      3 187466157 187466157     16 10969379 10969379    .   204       +       +        14-41461T  BCL6   CIITA CIITA-BCL6
 2:      3 187466157 187466157     16 10969379 10969379    .   204       +       +        14-41461T CIITA    BCL6 BCL6-CIITA
```

**Comment by vladimirsouza** [comment]
Taking @Kdreval's example above and showing `annotate_sv` output before and after my changes in this PR.

The new version correctly picks only the row where `gene` is BCL2.

```
library(dplyr)

# get input for annotated_sv
my_meta <- GAMBLR.results::get_gambl_metadata()
my_samples <- my_meta$sample_id
sv_df = GAMBLR.results::get_manta_sv(these_samples_metadata = my_meta, these_sample_ids = my_samples)

# collapsed values of the example above
collapsed_columns <- "3_187466157_187466157_16_10969379_10969379_._204_+_+_14-41461T"
```
**BEFORE** changes in this PR
```
# get annotated svs
library(GAMBLR.utils)
annotated_sv_old = annotate_sv(sv_data = sv_df)
# select rows of the example above
markers_old <- select(annotated_sv_old, !c(gene, partner, fusion)) %>% 
  tidyr::unite(all_cols_marker, everything(), remove = TRUE) %>% 
  unlist
filter(annotated_sv_old, markers_old == collapsed_columns)

#    chrom1    start1      end1 chrom2   start2     end2 name score strand1 strand2 tumour_sample_id  gene partner     fusion
# 1:      3 187466157 187466157     16 10969379 10969379    .   204       +       +        14-41461T  BCL6   CIITA CIITA-BCL6
# 2:      3 187466157 187466157     16 10969379 10969379    .   204       +       +        14-41461T CIITA    BCL6 BCL6-CIITA
```

**AFTER** changes in this PR
```
# get annotated svs
devtools::load_all("~/repos/gamblr_repos/GAMBLR.utils")
annotated_sv_new = annotate_sv(sv_data = sv_df)
# select rows of the example above
markers_old <- select(annotated_sv_old, !c(gene, partner, fusion)) %>% 
  tidyr::unite(all_cols_marker, everything(), remove = TRUE) %>% 
  unlist
filter(annotated_sv_old, markers_old == collapsed_columns)

#    chrom1    start1      end1 chrom2   start2     end2 name score strand1 strand2 tumour_sample_id gene partner     fusion
# 1:      3 187466157 187466157     16 10969379 10969379    .   204       +       +        14-41461T BCL6   CIITA CIITA-BCL6
```

**Comment by Kdreval** [comment]
This looks great! Thanks!

**Comment by Kdreval** [comment]
I think to finish it and merge let's make the `priority_to_be_oncogene <- c("MYC", "BCL6")` as a parameter with these values as default, so in case we want to modify or extend it in the future no changes to code will be required.

Thanks!

**Comment by vladimirsouza** [comment]
Yes! Thanks @Kdreval! I like this idea.

**Comment by vladimirsouza** [comment]
I'm going to remove the table in the documentation.

**Comment by vladimirsouza** [comment]
To check the results, I created a unique marker for each row &mdash; the values of all columns except `"gene"`, `"partner"` and `"fusion"` columns collapsed in a single string for each row. If there are rows with the same markers, it means that they may be duplicates. I split the rows based on the markers and got the pairs of rows with the same markers. Here are examples of two pairs:
```
$`18_61124288_61124289_18_61125635_61125636_._64_+_-_WGA_PD26416a`
   chrom1   start1     end1 chrom2   start2     end2 name score strand1 strand2 tumour_sample_id gene partner  fusion
1:     18 61124288 61124289     18 61125635 61125636    .    64       +       -     WGA_PD26416a BCL2    <NA> NA-BCL2
2:     18 61124288 61124289     18 61125635 61125636    .    64       +       -     WGA_PD26416a BCL2    <NA> NA-BCL2

$`3_71407687_71407689_3_187461220_187461222_._93_-_-_08-15460T`
   chrom1   start1     end1 chrom2    start2      end2 name score strand1 strand2 tumour_sample_id  gene partner     fusion
1:      3 71407687 71407689      3 187461220 187461222    .    93       -       -        08-15460T FOXP1    BCL6 BCL6-FOXP1
2:      3 71407687 71407689      3 187461220 187461222    .    93       -       -        08-15460T  BCL6   FOXP1 FOXP1-BCL6
```

I checked these pairs after using the `annotate_vs` versions before and after the changes of this PR and it seems that new version is handling duplicates very well &mdash; **no case of duplication.** See counts of pairs separated by cases 1 to 4 (cases described in my first post in this PR). 

* Before the changes of this PR:
```
                                                                        count_of_pairs
(no case)                                 no duplication:                    4128
(cases 1 or 2, or both partners are NAs)  rows 100% identical:               4111
(case 3)                                  not considered duplication           84
(case 4)                                  need to prioritize oncogene:         11
total:                                                                       8334
```

* After the changes of this PR:
```
                                                                        count_of_pairs
(no case)                                 no duplication:                    8250
(case 3)                                  not considered duplication           84
total:                                                                       8334
```

**Comment by vladimirsouza** [comment]
Here is an example how duplicate rows are handled when changing the new argument `priority_to_be_oncogene`

* duplicate rows before the filtering:
```
#    chrom1    start1      end1 chrom2   start2     end2 name score strand1 strand2 tumour_sample_id gene partner     fusion
# 1:      3 187459830 187459830     16 10974808 10974808    .    64       +       +         FL1013T2 BCL6   CIITA CIITA-BCL6
# 1:      3 187459830 187459830     16 10974808 10974808    .    64       +       +         FL1013T2 CIITA    BCL6 BCL6-CIITA
```

* using `priority_to_be_oncogene = c("MYC", "BCL6")` (default):
```
#    chrom1    start1      end1 chrom2   start2     end2 name score strand1 strand2 tumour_sample_id gene partner     fusion
# 1:      3 187459830 187459830     16 10974808 10974808    .    64       +       +         FL1013T2 BCL6   CIITA CIITA-BCL6
```

* using `priority_to_be_oncogene = "CIITA"`:
```
#    chrom1    start1      end1 chrom2   start2     end2 name score strand1 strand2 tumour_sample_id  gene partner     fusion
# 1:      3 187459830 187459830     16 10974808 10974808    .    64       +       +         FL1013T2 CIITA    BCL6 BCL6-CIITA
```

**Review by Kdreval — APPROVED** [review]
Thanks for the update!

**Pull request merged**
