### PR TITLE
Add build_browser_hub function

### PR DESCRIPTION
**Pull request by vladimirsouza**
An example of a track hub:
```
library(GAMBLR.data)

local_web_host_dir = "~/repos/LLMPP"
hub_dir = "hubs/ashm_test"

regions_bed = filter(GAMBLR.data::grch37_ashm_regions, gene == "BCL6")
my_meta = filter(sample_data$meta, pathology %in% c("BL", "DLBCL", "FL"))

build_browser_hub(
  regions_bed = regions_bed,
  these_samples_metadata = my_meta,
  this_seq_type = "genome",
  projection = "grch37",
  local_web_host_dir = local_web_host_dir,
  hub_dir = hub_dir,
  splitColumnName = "pathology",
  longLabel = "Public aSHM mutations separated by pathologies"
)
```

Here are the files that the function created:
```
(base) vsouza@gphost09:~/repos/LLMPP/hubs/ashm_test$ tree
.
├── grch37
│   ├── BL.bb
│   ├── DLBCL.bb
│   ├── FL.bb
│   └── regions.bb
└── hub.txt

1 directory, 5 files
```

And here the content of hub.txt:
```
(base) vsouza@gphost09:~/repos/LLMPP/hubs/ashm_test$ cat hub.txt
hub ashm_test
shortLabel ashm_test
longLabel Public aSHM mutations separated by pathologies
useOneFile on
email rdmorin@sfu.ca

genome hg19

track ashm_test_regions
shortLabel ashm_test regions
longLabel Regions where mutations were taken to hub ashm_test
visibility squish
priority 1
type bigBed
bigDataUrl https://github.com/morinlab/LLMPP/blob/main/hubs/ashm_test/grch37/regions.bb?raw=true

track ashm_test_BL
shortLabel ashm_test BL
longLabel ashm_test BL
visibility squish
priority 2
type bigBed
itemRgb on
bigDataUrl https://github.com/morinlab/LLMPP/blob/main/hubs/ashm_test/grch37/BL.bb?raw=true

track ashm_test_DLBCL
shortLabel ashm_test DLBCL
longLabel ashm_test DLBCL
visibility squish
priority 3
type bigBed
itemRgb on
bigDataUrl https://github.com/morinlab/LLMPP/blob/main/hubs/ashm_test/grch37/DLBCL.bb?raw=true

track ashm_test_FL
shortLabel ashm_test FL
longLabel ashm_test FL
visibility squish
priority 4
type bigBed
itemRgb on
bigDataUrl https://github.com/morinlab/LLMPP/blob/main/hubs/ashm_test/grch37/FL.bb?raw=true
```

### CODE REVIEW

**Comment by vladimirsouza** [comment]
There is a [PR in the LLMPP repo](https://github.com/morinlab/LLMPP/pull/2) with track hubs built by `build_browser_hub`. You can check their [visualization in the UCSC browser](https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg19&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=chr3%3A187439165%2D187463513&hgsid=1981808702_HKVDBPIm9G8g2wvFdjIOKsbxI0FZ).

**Comment by Kdreval** [comment]
is this ready to be re-reviewed @vladimirsouza ?

**Comment by vladimirsouza** [comment]
Yes. I just wanted to update the PR description before requesting reviews. 

Moreover, since this PR is linked to [this PR in LLMPP repo](https://github.com/morinlab/LLMPP/pull/2), I also want to update the latter. 

I'm working on these now.

**Comment by Kdreval** [comment]
Thank you! When ready, please start new PR to merge into master (not main) branch

**Pull request closed without merging**
